name = "smart-recipe-generator"
compatibility_date = "2024-01-01"

[env.production.vars]
# 在 Cloudflare Dashboard 中配置敏感信息
# GEMINI_API_KEYS = "key1,key2,key3"
# GEMINI_BASE_URL = "https://generativelanguage.googleapis.com"
